window.BENCHMARK_DATA = {
  "lastUpdate": 1781136874025,
  "repoUrl": "https://github.com/gianlucamazza/emotional-memory",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {
            "email": "info@gianlucamazza.it",
            "name": "Gianluca Mazza",
            "username": "gianlucamazza"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "e68d2cc4936b124fd96de027e610e4d604250977",
          "message": "research: Addendum Q — affect-aware gating (Branch C: routing line closed, gating is a safe wrapper) (#55)\n\n* docs(bench): freeze Addendum Q pre-registration — affect-aware gating (Hq1-Hq3)\n\nPre-register the gating study named as next angle in the Addendum P\nclosure: apply the affect channel only when the query is\naffect-discriminative. Confirmatory family (Holm m=3): Hq1 LLM-affect vs\ncosine on the affective subset (the untested quadrant), Hq2 gated vs\nalways-on dual, Hq3 gated vs cosine on the mixed corpus. Oracle-gate arm\nbounds classifier loss; gate accuracy reporting is mandatory (Hl3\nlesson). Dataset realistic_recall_v5_gate (qNN_ namespace, disjoint from\nv3/v4) with per-query gate_label ground truth and a mechanical\nlexical-leakage gate on the affective half.\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>\n\n* docs(bench): Addendum Q amendment 1 — gating as adapter-level front-router\n\nadaptive_weights() modulates routed weight vectors by current mood, so an\nengine-level [1,0,0,0,0,0] gate-off is not pure cosine mid-arc. Gate at\nthe adapter level instead: affect_free -> local cosine index shared with\nnaive_cosine (equivalence by construction), affective -> engine identical\nto aft_llm_dual. Pre-execution amendment, committed before the generator\nexists and before any data generation.\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>\n\n* feat(bench): Addendum Q infrastructure — gated runner, v5_gate generator, smoke tests\n\nrunner_hq.py: gate-labelled dataset models + acceptance-gate validation,\noracle and LLM binary gate classifiers (query-text-matched logging, Hl3\nlesson), front-router gated adapters per Amendment 1 (affect_free ->\nlocal cosine index shared with naive_cosine, affective -> engine\nidentical to aft_llm_dual, shared LLMAppraisalEngine across AFT arms),\nHq1-Hq3 confirmatory family with Holm m=3, Hq4-Hq6 exploratory reports,\nand a no-LLM dry-run asserting gate-off/naive-cosine top1 equivalence.\n\ngenerate_v5_gate.py: 50 fresh themes (qNN_ namespace, disjoint from\nv3/v4), frozen six-slot arc where the affective target e4 is\ntone-congruent with the arc end while its semantic distractor e5 is more\nrecent and opposite in tone, plus the mechanical lexical-leakage gate.\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>\n\n* chore(bench): freeze realistic_recall_v5_gate dataset (50 scenarios / 200 queries, pre-run)\n\nGenerated by generate_v5_gate.py (gpt-5-mini, one structured call per\nscenario). 100 affect-free + 100 affective queries (2/2 per scenario),\nqNN_ namespace disjoint from v3/v4, frozen six-slot arc with the\naffective target e4 tone-congruent with the arc end and the semantic\ndistractor e5 more recent and opposite in tone. The mechanical\nlexical-leakage gate rejected and regenerated ~8 first attempts.\nCommitted before any benchmark run (author-blind, pre-reg discipline).\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>\n\n* docs(bench): Addendum Q closure — Branch C, affect-routing line closed (Hq2 PASS retained)\n\nSingle pre-registered run (seed 0, sbert-bge, gpt-5-mini shared\nappraisal) on the frozen realistic_recall_v5_gate. Hq1 FAIL: LLM-inferred\naffect loses to cosine on the affective subset itself (0.090 vs 0.140;\nanchored tiebreak 0.160 vs 0.280). Hq3 FAIL (gated vs cosine -0.025);\nHq4: even the oracle-gate arm is significantly below cosine (-0.045,\np=0.0024) -- the bottleneck is the channel, not the gate (LLM gate\naccuracy 0.844, and the imperfect gate beats the perfect one because\nmisrouting to cosine helps). Hq2 PASS (+0.080, p_holm=0.0009): the\nfront-router recovers the entire always-on penalty exactly (gated ==\ncosine on the affect-free half, Hq5 delta=0.000 live).\n\nBranch C interpretation: state-based affect signals cannot answer\nquery-driven affect questions -- the oracle-affect boundary is also a\nstate-injection boundary (Hd-family protocols inject the query state\nbefore retrieval). Disclosed construction limitation: affective_arc_blind\nfloors for every system under cross-scenario accumulation (incl. one\nduplicate query text q06/q37); the verdict stands on the anchored\ntiebreak queries. Residual hypothesis, not scheduled: retrieve-time\nquery appraisal as a new signal.\n\nPropagated to claim matrix (appraisal_llm_real_dual_path), current\nevidence (table + prose section), limitations (state-injection boundary),\nROADMAP, CHANGELOG.\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>\n\n---------\n\nCo-authored-by: Claude Fable 5 <noreply@anthropic.com>",
          "timestamp": "2026-06-11T02:08:01+02:00",
          "tree_id": "5370dee63a953b11441990d8b4416b59a19ec041",
          "url": "https://github.com/gianlucamazza/emotional-memory/commit/e68d2cc4936b124fd96de027e610e4d604250977"
        },
        "date": 1781136873508,
        "tool": "pytest",
        "benches": [
          {
            "name": "benchmarks/perf/bench_encode.py::bench_encode_single",
            "value": 506.2086515508854,
            "unit": "iter/sec",
            "range": "stddev: 0.0009448778045373652",
            "extra": "mean: 1.9754699903612323 msec\nrounds: 1660"
          },
          {
            "name": "benchmarks/perf/bench_encode.py::bench_encode_with_resonance",
            "value": 448.881405310929,
            "unit": "iter/sec",
            "range": "stddev: 0.0010450343887573696",
            "extra": "mean: 2.2277599120135636 msec\nrounds: 1773"
          },
          {
            "name": "benchmarks/perf/bench_encode.py::bench_encode_no_resonance",
            "value": 383.06204325921425,
            "unit": "iter/sec",
            "range": "stddev: 0.001465860825408823",
            "extra": "mean: 2.61054316812932 msec\nrounds: 2165"
          },
          {
            "name": "benchmarks/perf/bench_encode.py::bench_encode_scaling[10]",
            "value": 192.94602954298367,
            "unit": "iter/sec",
            "range": "stddev: 0.003625033667986128",
            "extra": "mean: 5.182796465771401 msec\nrounds: 3798"
          },
          {
            "name": "benchmarks/perf/bench_encode.py::bench_encode_scaling[100]",
            "value": 434.41540022468973,
            "unit": "iter/sec",
            "range": "stddev: 0.0010784372161826824",
            "extra": "mean: 2.301944174821557 msec\nrounds: 1819"
          },
          {
            "name": "benchmarks/perf/bench_encode.py::bench_encode_scaling[1000]",
            "value": 363.3799127211483,
            "unit": "iter/sec",
            "range": "stddev: 0.00041744681958434454",
            "extra": "mean: 2.7519407787611625 msec\nrounds: 452"
          },
          {
            "name": "benchmarks/perf/bench_footprint.py::bench_memory_per_record",
            "value": 140227.32163073836,
            "unit": "iter/sec",
            "range": "stddev: 0.0000011319359678309392",
            "extra": "mean: 7.131277901986229 usec\nrounds: 46081"
          },
          {
            "name": "benchmarks/perf/bench_footprint.py::bench_store_footprint[100]",
            "value": 27.803543424435905,
            "unit": "iter/sec",
            "range": "stddev: 0.00021852624606912767",
            "extra": "mean: 35.96663866667882 msec\nrounds: 3"
          },
          {
            "name": "benchmarks/perf/bench_footprint.py::bench_store_footprint[1000]",
            "value": 0.8120120118403484,
            "unit": "iter/sec",
            "range": "stddev: 0.004398620018915515",
            "extra": "mean: 1.2315088759999924 sec\nrounds: 3"
          },
          {
            "name": "benchmarks/perf/bench_footprint.py::bench_store_footprint[5000]",
            "value": 0.026590745053134673,
            "unit": "iter/sec",
            "range": "stddev: 1.1128616009653851",
            "extra": "mean: 37.60706960266666 sec\nrounds: 3"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_resonance_build[50]",
            "value": 3277.250158849249,
            "unit": "iter/sec",
            "range": "stddev: 0.000013246041660177483",
            "extra": "mean: 305.13386269882216 usec\nrounds: 2083"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_resonance_build[200]",
            "value": 896.9250880990345,
            "unit": "iter/sec",
            "range": "stddev: 0.00001549020056375962",
            "extra": "mean: 1.1149203130435619 msec\nrounds: 690"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_resonance_build[500]",
            "value": 366.7666413302138,
            "unit": "iter/sec",
            "range": "stddev: 0.00008827955692488585",
            "extra": "mean: 2.7265293167697395 msec\nrounds: 322"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_encode_with_large_resonance_graph",
            "value": 491.65928430443574,
            "unit": "iter/sec",
            "range": "stddev: 0.0007887698388246812",
            "extra": "mean: 2.033928844473522 msec\nrounds: 778"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_spreading_activation[100-1]",
            "value": 10814.645212107387,
            "unit": "iter/sec",
            "range": "stddev: 0.000004915892981882051",
            "extra": "mean: 92.46720353622547 usec\nrounds: 4864"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_spreading_activation[100-2]",
            "value": 10590.674275384457,
            "unit": "iter/sec",
            "range": "stddev: 0.0000044656884267772955",
            "extra": "mean: 94.42269434385928 usec\nrounds: 8009"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_spreading_activation[500-1]",
            "value": 1851.511915281193,
            "unit": "iter/sec",
            "range": "stddev: 0.000018103040030656225",
            "extra": "mean: 540.0991437033922 usec\nrounds: 1183"
          },
          {
            "name": "benchmarks/perf/bench_resonance.py::bench_spreading_activation[500-2]",
            "value": 1845.2499402314693,
            "unit": "iter/sec",
            "range": "stddev: 0.000011480747254989447",
            "extra": "mean: 541.9320050890013 usec\nrounds: 1572"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_top5[100]",
            "value": 1022.4849273487414,
            "unit": "iter/sec",
            "range": "stddev: 0.000021650118820189308",
            "extra": "mean: 978.0095268425678 usec\nrounds: 801"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_top5[1000]",
            "value": 374.8676442349148,
            "unit": "iter/sec",
            "range": "stddev: 0.00011667915005357909",
            "extra": "mean: 2.667608195529778 msec\nrounds: 358"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_top5[10000]",
            "value": 21.678504034784034,
            "unit": "iter/sec",
            "range": "stddev: 0.001269902394547857",
            "extra": "mean: 46.12864422727047 msec\nrounds: 22"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_varying_topk[1]",
            "value": 472.7412099978269,
            "unit": "iter/sec",
            "range": "stddev: 0.000060092939949026104",
            "extra": "mean: 2.115322249999311 msec\nrounds: 452"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_varying_topk[5]",
            "value": 378.2523459539209,
            "unit": "iter/sec",
            "range": "stddev: 0.00007983844496950614",
            "extra": "mean: 2.643737734072959 msec\nrounds: 361"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_varying_topk[10]",
            "value": 307.92655425146944,
            "unit": "iter/sec",
            "range": "stddev: 0.00008875609614629125",
            "extra": "mean: 3.2475276529199424 msec\nrounds: 291"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_varying_topk[25]",
            "value": 194.88533562218493,
            "unit": "iter/sec",
            "range": "stddev: 0.00014540795429549886",
            "extra": "mean: 5.131222402175262 msec\nrounds: 184"
          },
          {
            "name": "benchmarks/perf/bench_retrieve.py::bench_retrieve_with_reconsolidation",
            "value": 854.9079806238301,
            "unit": "iter/sec",
            "range": "stddev: 0.000020296353667291308",
            "extra": "mean: 1.1697165340184281 msec\nrounds: 779"
          }
        ]
      }
    ]
  }
}