"""Reproduce all paper tables from the emotional-memory benchmark suite.

Usage::

    uv run python scripts/reproduce_paper.py [--out-dir paper/tables]

Outputs
-------
paper/tables/table1_fidelity.md   — fidelity benchmark summary (pass/fail per phenomenon)
paper/tables/table2_perf.md       — performance p50/p95 latency table
paper/tables/table3_comparative.md — comparative recall@k vs baselines (if available)

The script is designed to be tolerant of missing artefacts:
- If benchmark-results.json does not exist, Table 2 is skipped with a warning.
- If benchmarks/comparative/results.csv does not exist, Table 3 is marked
  "not evaluated" — run `make bench-comparative` to generate it.
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import textwrap
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).parent.parent
BENCH_RESULTS = ROOT / "benchmark-results.json"
COMPARATIVE_CSV = ROOT / "benchmarks" / "comparative" / "results.csv"
FIDELITY_DIR = ROOT / "benchmarks" / "fidelity"


# ---------------------------------------------------------------------------
# Table 1 — fidelity benchmark summary
# ---------------------------------------------------------------------------


def _run_fidelity(out_dir: Path) -> None:
    xml_path = out_dir / "_fidelity_junit.xml"
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "pytest",
            str(FIDELITY_DIR),
            "-v",
            "-m",
            "fidelity",
            f"--junit-xml={xml_path}",
            "--tb=no",
            "-q",
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )

    # Parse JUnit XML (present even on partial failure)
    if not xml_path.exists():
        print(f"[WARN] fidelity JUnit XML not produced — pytest exit {result.returncode}")
        print(result.stdout[-2000:] if result.stdout else "")
        return

    tree = ET.parse(xml_path)
    root = tree.getroot()

    rows: list[tuple[str, int, int]] = []
    for testsuite in root.iter("testsuite"):
        name = testsuite.get("name", "unknown")
        tests = int(testsuite.get("tests", 0))
        failures = int(testsuite.get("failures", 0)) + int(testsuite.get("errors", 0))
        passed = tests - failures
        rows.append((name, passed, tests))

    xml_path.unlink(missing_ok=True)

    total_passed = sum(r[1] for r in rows)
    total_tests = sum(r[2] for r in rows)

    lines = [
        "# Table 1 — Fidelity benchmark summary",
        "",
        "| Test module | Passed | Total | Rate |",
        "| --- | ---: | ---: | ---: |",
    ]
    for name, passed, total in sorted(rows):
        rate = f"{100 * passed / total:.0f}%" if total > 0 else "—"
        # strip path prefix for readability
        short = name.replace("benchmarks/fidelity/", "").replace(".py", "")
        lines.append(f"| {short} | {passed} | {total} | {rate} |")

    lines += [
        f"| **Total** | **{total_passed}** | **{total_tests}** | "
        f"**{100 * total_passed / total_tests:.0f}%** |",
        "",
        f"_Generated by `make reproduce-paper`. Pytest exit code: {result.returncode}_",
    ]

    out = out_dir / "table1_fidelity.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"[OK] Table 1 written → {out.relative_to(ROOT)}")

    # LaTeX tabular fragment (booktabs) — used by \input{tables/table1_fidelity.tex}
    rate_total = f"{100 * total_passed / total_tests:.0f}\\%" if total_tests > 0 else "---"
    tex_lines = [
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "\\textbf{Test module} & \\textbf{Passed} & \\textbf{Total} & \\textbf{Rate} \\\\",
        "\\midrule",
    ]
    for name, passed, total in sorted(rows):
        rate = f"{100 * passed / total:.0f}\\%" if total > 0 else "---"
        short = name.replace("benchmarks/fidelity/", "").replace(".py", "").replace("_", "\\_")
        tex_lines.append(f"{short} & {passed} & {total} & {rate} \\\\")
    tex_lines += [
        "\\midrule",
        (
            f"\\textbf{{Total}} & \\textbf{{{total_passed}}} & "
            f"\\textbf{{{total_tests}}} & \\textbf{{{rate_total}}} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
    ]
    tex_out = out_dir / "table1_fidelity.tex"
    tex_out.write_text("\n".join(tex_lines) + "\n")
    print(f"[OK] Table 1 LaTeX written → {tex_out.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Table 2 — performance latency
# ---------------------------------------------------------------------------


def _write_perf_table(out_dir: Path) -> None:
    if not BENCH_RESULTS.exists():
        msg = textwrap.dedent("""\
            # Table 2 — Performance benchmarks

            _Not evaluated: `benchmark-results.json` not found._
            _Run `make bench-perf` to generate it._
        """)
        out = out_dir / "table2_perf.md"
        out.write_text(msg)
        print("[WARN] Table 2: benchmark-results.json missing — placeholder written")
        return

    with BENCH_RESULTS.open() as f:
        data = json.load(f)

    benchmarks = data.get("benchmarks", [])
    lines = [
        "# Table 2 — Performance benchmarks",
        "",
        "| Operation | Mean (ms) | Median (ms) | p95 (ms) | Rounds |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for b in benchmarks:
        name = b.get("name", "?")
        stats = b.get("stats", {})
        mean = stats.get("mean", 0) * 1000
        median = stats.get("median", 0) * 1000
        p95 = stats.get("q95", stats.get("p95", stats.get("max", 0))) * 1000
        rounds = stats.get("rounds", "?")
        lines.append(f"| {name} | {mean:.2f} | {median:.2f} | {p95:.2f} | {rounds} |")

    lines += ["", "_Generated by `make reproduce-paper`._"]
    out = out_dir / "table2_perf.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"[OK] Table 2 written → {out.relative_to(ROOT)}")

    # LaTeX tabular fragment (booktabs) — used by \input{tables/table2_perf.tex}
    tex_lines = [
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        (
            "\\textbf{Operation} & \\textbf{Mean (ms)} & \\textbf{Median (ms)} & "
            "\\textbf{p95 (ms)} & \\textbf{Rounds} \\\\"
        ),
        "\\midrule",
    ]
    for b in benchmarks:
        name = b.get("name", "?").replace("_", "\\_")
        stats = b.get("stats", {})
        mean = stats.get("mean", 0) * 1000
        median = stats.get("median", 0) * 1000
        p95 = stats.get("q95", stats.get("p95", stats.get("max", 0))) * 1000
        rounds = stats.get("rounds", "?")
        tex_lines.append(f"{name} & {mean:.2f} & {median:.2f} & {p95:.2f} & {rounds} \\\\")
    tex_lines += ["\\bottomrule", "\\end{tabular}"]
    tex_out = out_dir / "table2_perf.tex"
    tex_out.write_text("\n".join(tex_lines) + "\n")
    print(f"[OK] Table 2 LaTeX written → {tex_out.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Table 3 — comparative recall@k
# ---------------------------------------------------------------------------


def _write_comparative_table(out_dir: Path) -> None:
    if not COMPARATIVE_CSV.exists():
        placeholder = textwrap.dedent("""\
            # Table 3 — Comparative benchmark

            _Not evaluated: `benchmarks/comparative/results.csv` not found._
            _Run `make bench-comparative` to generate it._
        """)
        (out_dir / "table3_comparative.md").write_text(placeholder)
        (out_dir / "table3_comparative.tex").write_text(
            "% Table 3 — not evaluated (run make bench-comparative)\n"
            "% \\input{tables/table3_comparative.tex}\n"
        )
        print("[WARN] Table 3: comparative results.csv missing — placeholder written")
        return

    with COMPARATIVE_CSV.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        (out_dir / "table3_comparative.md").write_text(
            "# Table 3 — Comparative benchmark\n\n_results.csv is empty._\n"
        )
        return

    # Markdown table
    headers = list(rows[0].keys())
    md_lines = [
        "# Table 3 — Comparative benchmark",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    md_lines.extend("| " + " | ".join(row.get(h, "—") for h in headers) + " |" for row in rows)
    md_lines += ["", "_Generated by `make reproduce-paper`._"]
    (out_dir / "table3_comparative.md").write_text("\n".join(md_lines) + "\n")

    # LaTeX tabular fragment (booktabs) — used by \input{tables/table3_comparative.tex}
    # Display columns: system, recall@k, encode_ms_avg, retrieve_p50_ms, retrieve_p95_ms
    k = rows[0].get("top_k", "5")
    tex_lines = [
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        (
            "\\textbf{System} & \\textbf{Recall@" + str(k) + "}"
            " & \\textbf{Encode ms} & \\textbf{p50 ms} & \\textbf{p95 ms} \\\\"
        ),
        "\\midrule",
    ]
    for row in rows:
        recall = row.get(f"recall@{k}", "—")
        enc = row.get("encode_ms_avg", "—")
        p50 = row.get("retrieve_p50_ms", "—")
        p95 = row.get("retrieve_p95_ms", "—")
        sys_name = row["system"].replace("_", "\\_")
        if row.get("status") == "ok":
            tex_lines.append(f"{sys_name} & {recall} & {enc} & {p50} & {p95} \\\\")
        else:
            reason = row.get("reason", row.get("status", ""))[:40]
            tex_lines.append(f"{sys_name} & \\multicolumn{{4}}{{l}}{{\\textit{{{reason}}}}} \\\\")
    tex_lines += [
        "\\bottomrule",
        "\\end{tabular}",
    ]
    (out_dir / "table3_comparative.tex").write_text("\n".join(tex_lines) + "\n")

    out = out_dir / "table3_comparative.md"
    print(f"[OK] Table 3 written → {out.relative_to(ROOT)} + .tex")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Reproduce paper tables.")
    parser.add_argument(
        "--out-dir",
        default=str(ROOT / "paper" / "tables"),
        help="Directory to write output Markdown tables (default: paper/tables/)",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("=== Reproducing paper tables ===")
    print(f"Output directory: {out_dir.relative_to(ROOT)}")
    print()

    print("--- Table 1: Fidelity benchmarks ---")
    _run_fidelity(out_dir)
    print()

    print("--- Table 2: Performance benchmarks ---")
    _write_perf_table(out_dir)
    print()

    print("--- Table 3: Comparative benchmark ---")
    _write_comparative_table(out_dir)
    print()

    print("Done. Tables written to:", out_dir.relative_to(ROOT))


if __name__ == "__main__":
    main()
